build(pgpool): Succes on lab.

diff --git a/templates/scripts/failover.repmgr.sh.j2 b/templates/scripts/failover.repmgr.sh.j2
--- a/templates/scripts/failover.repmgr.sh.j2
+++ b/templates/scripts/failover.repmgr.sh.j2
@@ -1,73 +1,84 @@
 #!/bin/bash
+# This script is run by failover_command.
+
+set -o xtrace
 
 # Special values:
-#   %d = failed node id
-#   %h = failed node hostname
-#   %p = failed node port number
-#   %D = failed node database cluster path
-#   %m = new master node id
-#   %H = new master node hostname
-#   %M = old master node id
-#   %P = old primary node id
-#   %r = new master port number
-#   %R = new master database cluster path
-#   %N = old primary node hostname
-#   %S = old primary node port number
-#   %% = '%' character
-# ex input : 0 pgsql01 5432 /var/lib/postgresql/12/main 1 pgsql02 0 0 5432 /var/lib/postgresql/12/main pgsql01 5432
+# 1)  %d = failed node id
+# 2)  %h = failed node hostname
+# 3)  %p = failed node port number
+# 4)  %D = failed node database cluster path
+# 5)  %m = new main node id
+# 6)  %H = new main node hostname
+# 7)  %M = old main node id
+# 8)  %P = old primary node id
+# 9)  %r = new main port number
+# 10) %R = new main database cluster path
+# 11) %N = old primary node hostname
+# 12) %S = old primary node port number
+# 13) %% = '%' character
 
 FAILED_NODE_ID="$1"
 FAILED_NODE_HOST="$2"
 FAILED_NODE_PORT="$3"
 FAILED_NODE_PGDATA="$4"
-NEW_MASTER_NODE_ID="$5"
-NEW_MASTER_NODE_HOST="$6"
-OLD_MASTER_NODE_ID="$7"
+NEW_MAIN_NODE_ID="$5"
+NEW_MAIN_NODE_HOST="$6"
+OLD_MAIN_NODE_ID="$7"
 OLD_PRIMARY_NODE_ID="$8"
-NEW_MASTER_NODE_PORT="$9"
-NEW_MASTER_NODE_PGDATA="${10}"
+NEW_MAIN_NODE_PORT="$9"
+NEW_MAIN_NODE_PGDATA="${10}"
 OLD_PRIMARY_NODE_HOST="${11}"
 OLD_PRIMARY_NODE_PORT="${12}"
-SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
 
-(
-date
-echo "FAILED_NODE_ID: $FAILED_NODE_ID"
-echo "FAILED_NODE_HOST: $FAILED_NODE_HOST"
-echo "FAILED_NODE_PORT: $FAILED_NODE_PORT"
-echo "FAILED_NODE_PGDATA: $FAILED_NODE_PGDATA"
-echo "NEW_MASTER_NODE_ID: $NEW_MASTER_NODE_ID"
-echo "NEW_MASTER_NODE_HOST: $NEW_MASTER_NODE_HOST"
-echo "OLD_MASTER_NODE_ID: $OLD_MASTER_NODE_ID"
-echo "OLD_PRIMARY_NODE_ID: $OLD_PRIMARY_NODE_ID"
-echo "NEW_MASTER_NODE_PORT: $NEW_MASTER_NODE_PORT"
-echo "NEW_MASTER_NODE_PGDATA: $NEW_MASTER_NODE_PGDATA"
-echo "OLD_PRIMARY_NODE_HOST: $OLD_PRIMARY_NODE_HOST"
-echo "OLD_PRIMARY_NODE_PORT: $OLD_PRIMARY_NODE_PORT"
+PGHOME=/usr/bin/
+REPL_SLOT_NAME=${FAILED_NODE_HOST//[-.]/_}
+POSTGRESQL_STARTUP_USER=postgres
+SSH_KEY_FILE=id_rsa_pgpool
+SSH_OPTIONS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/.ssh/${SSH_KEY_FILE}"
 
-echo "failover.sh: BEGIN - failed_node_id=${FAILED_NODE_ID} old_primary_node_id=${OLD_PRIMARY_NODE_ID} failed_host=${FAILED_NODE_HOST} new_master_host=${NEW_MASTER_NODE_HOST}"
 
-## If there's no master node anymore, skip failover.
-if [ ${NEW_MASTER_NODE_ID} -lt 0 ]; then
-  echo "failover.sh: All nodes are down. Skipping failover."
-  exit 0
+echo failover.sh: start: failed_node_id=$FAILED_NODE_ID failed_host=$FAILED_NODE_HOST \
+    old_primary_node_id=$OLD_PRIMARY_NODE_ID new_main_node_id=$NEW_MAIN_NODE_ID new_main_host=$NEW_MAIN_NODE_HOST
+
+## If there's no main node anymore, skip failover.
+if [ $NEW_MAIN_NODE_ID -lt 0 ]; then
+    echo failover.sh: All nodes are down. Skipping failover.
+    exit 0
 fi
 
 ## Test passwordless SSH
-ssh -T ${SSH_OPTS} ${NEW_MASTER_NODE_HOST} ls /tmp > /dev/null
+ssh -T ${SSH_OPTIONS} ${POSTGRESQL_STARTUP_USER}@${NEW_MAIN_NODE_HOST} ls /tmp > /dev/null
+
 if [ $? -ne 0 ]; then
-  echo "failover.sh: passwordless SSH to postgres@${NEW_MASTER_NODE_HOST} failed. Please setup passwordless SSH."
-  exit 1
+    echo failover.sh: passwordless SSH to ${POSTGRESQL_STARTUP_USER}@${NEW_MAIN_NODE_HOST} failed. Please setup passwordless SSH.
+    exit 1
+fi
+
+## If Standby node is down, skip failover.
+if [ $OLD_PRIMARY_NODE_ID != "-1" -a $FAILED_NODE_ID != $OLD_PRIMARY_NODE_ID ]; then
+
+    # If Standby node is down, drop replication slot.
+    ${PGHOME}/bin/psql -h ${OLD_PRIMARY_NODE_HOST} -p ${OLD_PRIMARY_NODE_PORT} postgres \
+        -c "SELECT pg_drop_replication_slot('${REPL_SLOT_NAME}');"  >/dev/null 2>&1
+
+    if [ $? -ne 0 ]; then
+        echo ERROR: failover.sh: drop replication slot \"${REPL_SLOT_NAME}\" failed. You may need to drop replication slot manually.
+    fi
+
+    echo failover.sh: end: standby node is down. Skipping failover.
+    exit 0
 fi
 
 ## Promote Standby node.
-if [ ${FAILED_NODE_ID} = ${OLD_PRIMARY_NODE_ID} ] ; then
-  echo "failover.sh: Primary node is down, promote standby node ${NEW_MASTER_NODE_HOST}."
-  ssh ${SSH_OPTS} ${NEW_MASTER_NODE_HOST} "/usr/bin/repmgr standby promote -f /etc/repmgr.conf --log-to-file -v"
-else
-  echo "failover.sh: Old primary id is ${OLD_PRIMARY_NODE_ID} and falling node id is ${FAILED_NODE_ID}."
+echo failover.sh: primary node is down, promote new_main_node_id=$NEW_MAIN_NODE_ID on ${NEW_MAIN_NODE_HOST}.
+
+ssh -T ${SSH_OPTIONS} ${POSTGRESQL_STARTUP_USER}@${NEW_MAIN_NODE_HOST} ${PGHOME}/bin/pg_ctlcluster -D ${NEW_MAIN_NODE_PGDATA} -w promote
+
+if [ $? -ne 0 ]; then
+    echo ERROR: failover.sh: end: failover failed
+    exit 1
 fi
 
-echo "failover.sh: END - new_master_node_id=${NEW_MASTER_NODE_ID} started as the primary node."
-exit 0;
-) 2>&1 | tee -a {{ pgpool_logdir }}/pgpool.log
+echo failover.sh: end: new_main_node_id=$NEW_MAIN_NODE_ID on ${NEW_MAIN_NODE_HOST} is promoted to a primary
+exit 0
